spring.application.name=backend
server.port=8081
# Enable cache headers for static resources
spring.web.resources.cache.cachecontrol.max-age=365d
spring.web.resources.cache.cachecontrol.cache-public=true
spring.web.resources.cache.cachecontrol.immutable=true
spring.devtools.restart.exclude=static/**,public/**,templates/**